### ISSUE TITLE
Error when loading existing world on 4.3.6 extended

### ISSUE THREAD

**Issue by msgerbs** [TerraFirmaGreg-Team/TFG-Modpack-1.12.x#208]
### Version modpack Used

Extended

### Environment

Forge Server

### Side Crashed

Server

### New Worlds

No

### Steps to Reproduce

Upgrading from 4.2.8 to 4.3.6. Removed everything except server.properties and world folder, copied in new server files, started server. Server loads fine, gives internal server error and disconnects the client when trying to join the server. Others on Discord reported similar issue.

### Crash Report

https://pastebin.com/gxx4eSB0

**Comment by Xikaro** [comment]
remove from server TFC  TooHotAroundHere

**Comment by Xikaro** [comment]
it shouldn't be there

**Comment by msgerbs** [comment]
I don't appear to have that mod, it's not in the server pack or the log file as far as I can see.

**Comment by Xikaro** [comment]
thah-1.2.0.jar

**Comment by msgerbs** [comment]
Looks like that worked. Guess that mod needs to be removed from the server pack.

**Comment by Xikaro** [comment]
![Screenshot_277](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.12.x/assets/55663835/214ac95d-1e77-421d-9dd2-e929a1524eb8)
it looks like the script missed it
