### ISSUE TITLE
Не могу зайти на дискорд сервер

### ISSUE THREAD

**Issue by EgorLetov1964** [TerraFirmaGreg-Team/TFG-Modpack-1.12.x#211]
### Ваш вопрос

Здравствуйте, я не могу зайти в дискорд сервер.Возможно меня на нем забанили, тк ранее мой аккаунт дискорд был взломан и с него отправлялась рассылка вирусного ПО. как я могу связаться с админиистрацией и поговорить, попросить о разбане. Или в чем может быть причина?

![Screenshot_4](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.12.x/assets/76592005/9b7b04e3-9f1e-4a14-bbb6-2822edbfae45)

**Comment by Xikaro** [comment]
Скинь ник

**Comment by Xikaro** [comment]
по какой ссылки входишь?

**Comment by Xikaro** [comment]
[terrafirmagreg](https://discord.gg/terrafirmagreg)

**Comment by EgorLetov1964** [comment]
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.12.x/assets/76592005/f2a6caf0-c825-44d3-8264-4eb04adb422c)

**volfgan_shwarz**

**Comment by Xikaro** [comment]
volfgan_shwarz
этот в бане, второй вроде нет
Я по ссылке захожу
с доп акков тоже

**Comment by EgorLetov1964** [comment]
Может по ip забанили? Можно, я не знаю разбан получить?

**Comment by Xikaro** [comment]
проверь

**Comment by EgorLetov1964** [comment]
Ура,спасибо огромное
